### PR TITLE
Pass arguments when invoking eb:config a second time in deploy task

### PR DESCRIPTION
**Pull request by jabr**
This fixes the issue I described in issue #12.

### CODE REVIEW

**Comment by rosskevin** [comment]
@jabr is this working for you?  I haven't gotten back to revisit and deploy to the new container yet, happy to merge on your approval.

**Comment by onomated** [comment]
Hi @rosskevin, this works for me.  Without @jabr changes, the `show_config` and `deploy` tasks do not use the provided `environment` and `version`.  Can we get an official release soon?
Thanks for an awesome gem.

**Comment by rosskevin** [comment]
@onomated v1.1.3 pushed

**Comment by jabr** [comment]
Sorry for the delayed response, but yes, I've been using this branch without issue for a while now.

**Comment by onomated** [comment]
Thanks @rosskevin!

**Pull request merged**
