### PR TITLE
changes necessary to use AWS-SDK 2.0 - referenced by eb_deployer

### PR DESCRIPTION
**Pull request by aterreno**
Fix for https://github.com/alienfast/elastic-beanstalk/issues/19

Let me know what you think - just deployed happily a rails test app with this version.

### CODE REVIEW

**Comment by rosskevin** [comment]
What version of eb_deployer are you using?  I'm thinking you should also put a min version for eb_deployer in the gemspec, that way older installs will pickup the new dependency.

**Comment by aterreno** [comment]
I've also found other stuff broken (around RDS, as you mentioned earlier).

**Comment by rosskevin** [comment]
eb_deployer 6.1 is what you have tested with?

**Comment by aterreno** [comment]
On Fri, Aug 14, 2015 at 4:59 PM, Kevin Ross <notifications@github.com>
wrote:

> eb_deployer 6.1 is what you have tested with?
>

    eb_deployer (0.6.1)
      aws-sdk (~> 2, >= 2.0.0)

**Comment by aterreno** [comment]
working on the rds tasks..

they changed massively the object structure

**Pull request merged**
