### PR TITLE
Support environment variable interpolation

### LINKED ISSUE #29: Unable to access environment variables in config.rb
I ran into this problem, when I wanted to add some variables to a server. Examples include:

+ GITHUB_TOKEN: <%= ENV["GITHUB_TOKEN"] %>
+ secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

### PR DESCRIPTION
**Pull request by djsegal**
Resolves #29

### CODE REVIEW

**Comment by djsegal** [comment]
writing a test now

**Comment by djsegal** [comment]
@rosskevin just wrote the test. i was wondering if it's kosher to use `ENV['TEST_VAR'] = 'TEST_VALUE'`, though. I was toying around with maybe having a holder value or something, but wanted to get your input first

**Comment by rosskevin** [comment]
That sounds fine, we can always alter it later if necessary.

**Comment by rosskevin** [comment]
v1.1.11 released, thank you

**Pull request merged**
